# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'RabbitMQDemo' do
pod 'RMQClient', '~> 0.7'
end
